# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'chatDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

    pod 'kk_chat'
    pod 'SnapKit'
    
end
